services:
  - type: web
    name: clktech-backend
    env: node
    buildCommand: |
      npm install
      npm run build:backend
    startCommand: NODE_ENV=production node dist/server/server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /api/health