services:
  - type: web
    name: clktech-backend
    env: node
    buildCommand: |
      npm install --no-package-lock
      cd client && npm install --no-package-lock && cd ..
      cd server && npm install --no-package-lock && cd ..
      npm run build
    startCommand: cross-env NODE_ENV=production node dist/server/server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /api/health